<?php

/**
 * Implements hook_block_info().
 */
function sbp_translation_block_info() {
  $blocks = array();
  $blocks['sbp_translation_icon'] = array(
    'info' => t('SBP Header Translation Icon'),
  );
  $blocks['sbp_translation_form'] = array(
    'info' => t('SBP Header Translation Form'),
  );
  return $blocks;
}

/**
 * Implements hook_block_configure().
 */
function sbp_translation_block_configure($delta = '') {
  $form = array();
  switch ($delta) {
  }
  return $form;
}

/**
 * Implements hook_block_save().
 */
function sbp_translation_block_save($delta = '', $edit = array()) {
  switch ($delta) {
  }
}

/**
 * Implements hook_block_view().
 */
function sbp_translation_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'sbp_translation_icon':
      $image = theme_image(array(
        'path' => drupal_get_path('module', 'sbp_translation') . '/images/icon-search-trans.png',
        'alt' => 'Translate',
        'attributes' => array('class'=>'sbp-translation-icon'),
      ));
      $block['content'] = array(
        'icon' => array(
          '#type' => 'markup',
          '#markup' => $image,
        ),
      );
      break;
    case 'sbp_translation_form':
      $block['content'] = _sbp_translation_widget_form();
      break;
  }
  return $block;
}

/**
 * Custom callback to render widget markup.
 */
function _sbp_translation_widget_form() {
  $styles = '<style type="text/css">span.search-title{color:#48bcfc;font-family:Merriweather, sans-serif;font-size:18px;padding-left:15px;padding-bottom:15px;}</style>';
  $search = '<script async src="https://cse.google.com/cse.js?cx=005429695907693588015:wcr_oo87bhe"></script><img src="/profiles/labp/modules/bp/custom/sbp_translation/images/icon-search-blue.png" width="20" height="20" alt="Search Business Knowledge" /><span class="search-title">Search Business Knowledge</span><div id="google_search_element" class="gcse-search"></div><style type="text/css">.cse .gsc-control-cse, .gsc-control-cse{padding:0 !important;}</style>';
  $markup = "$search<br /><br /><img src=\"/profiles/labp/modules/bp/custom/sbp_translation/images/icon-google-translate-blue.png\" width=\"20\" height=\"20\" alt=\"Switch to Another Language\"/><span class=\"search-title\">Switch to Another Language</span><div id=\"google_translate_element\"></div>
<script type=\"text/javascript\">
  function googleTranslateElementInit() {
	new google.translate.TranslateElement({pageLanguage: 'en', includedLanguages: 'en,zh-TW,es,ja,ru,tl,vi,ko,pt-PT,iw,ar', layout: google.translate.TranslateElement.InlineLayout.HORIZONTAL, autoDisplay: false},'google_translate_element');
  }
</script>
<noscript>Unable to load google translation scripts.</noscript>
<script type=\"text/javascript\" src=\"//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit\"></script>
<noscript>Unable to load google translation scripts.</noscript>$styles";
  return $markup;
}